### ISSUE TITLE
MIPCL does not run on Mac Catalina

### ISSUE THREAD

**Issue by zhi-e-yuan** [onebitbrain/MIPCL#3]
Firstly, the MIPCL mentioned in readme, www.mipcl-cpp.appspot.com, has error 404 cannot open. 

After forking the master, running command `./install_libs` gives error: Neither /usr/local/lib nor /usr/lib exists

Following all the installation steps, running binary bin/mps_mipcl gives error: MIPCL/bin/mps_mipcl: cannot execute binary file: Exec format error

Please help.

**Comment by onebitbrain** [comment]
Sorry, but I didn't write the code and it has been a long time since I used it. I don't know what happened to the site or the author but some of it is on the archive.org. Maybe try downloading a zip from the [https://github.com/onebitbrain/MIPCL/releases](url) I think the libs will exist in zip files.  I was going to archive the source since I thought it would be valuable to have another open source solver but I forgot and now it seems to be gone.

**Comment by zhi-e-yuan** [comment]
Hi Thanks a lot. I can now download the source code version 1.4.0, running
the ./install_libs seems to work. Could you please kindly advise how to run
it on a generic .mps or .lp file? All the binaries in the bin/ folder gives
me the error:

./mps_mipcl: cannot execute binary file: Exec format error


Do I need to compile the source code? If so, could you please kindly advise
how?

**Comment by onebitbrain** [comment]
Exec format error means it would need to be run in a virtual machine. I don't think compilation is possible any more
